### ISSUE TITLE
source: reddit

### ISSUE THREAD

**Issue by gdesmarais** [gdesmarais/video_downloader#1]
Allow configuration on per-subreddit basis.

First idea to download the videos from /r/youtube:

```
reddit:
  youtube:
   sort: top
   count: 10
   timerange: month
```
